version: '3'
  
services:
    cloudbeaver:
        image: dbeaver/cloudbeaver:latest
        container_name: cloudbeaver
        restart: always
        network_mode: host
        ports:
          - 8978:8978
        environment:
          - CB_LOCAL_HOST_ADDR=x.x.x.x
        volumes:
          - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace