version: '3'

services:
    nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: nginx-proxy-manager
    restart: always
    network_mode: bridge
    ports:
      - 8181:8181
      - 80:8080
      - 443:4443
    environment:
    DISABLE_IPV6: 'true'
    volumes:
      - "./nginx-proxy-manager/data:/config:rw"