version: '3'
  
services:
    postgres:
        image: postgres:14.0
        container_name: postgresql
        restart: always
        network_mode: bridge
        volumes:
          - ./postgresql/data:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432